src/mainwindow.ui

This adds Ctrl+P as keyboard shortcut to the File -> Print menue entry.

Added keyboard shortcut to print.

---

src/translations/lximage-qt-screenshot_de.desktop
src/translations/lximage-qt_ca.ts
src/translations/lximage-qt_de.desktop
src/translations/lximage-qt_de.ts
src/translations/lximage-qt_es.ts
src/translations/lximage-qt_gl.ts
src/translations/lximage-qt_hr.ts
src/translations/lximage-qt_id.ts
src/translations/lximage-qt_is.ts
src/translations/lximage-qt_ja.ts
src/translations/lximage-qt_pa.ts
src/translations/lximage-qt_pl.ts
src/translations/lximage-qt_pt.ts
src/translations/lximage-qt_pt_BR.ts
src/translations/lximage-qt_ru.ts
src/translations/lximage-qt_sv.ts
src/translations/lximage-qt_template.ts
src/translations/lximage-qt_zh_CN.ts
src/translations/lximage-qt_zh_TW.ts

Here is the german translation.
Because source files have been changed (and some strings were added) I re-generated all other .ts files, too. So they become visible to other translators.

Added german translation, re-generated all other .ts files.

---

src/application.cpp
src/application.h
src/mainwindow.cpp
src/mainwindow.h
src/settings.cpp
src/settings.h

To address issue #22, no gui option, more or less just copied from pcmanfm-qt.

save and restore window size and maximized state

---

src/preferencesdialog.ui

Prevents the slideshow interval to be set to 0 in the UI

---

src/application.cpp
src/application.h
src/imageview.h
src/loadimagejob.cpp
src/mainwindow.cpp
src/mainwindow.h
src/org.lxde.LxImage.Application.xml
src/preferencesdialog.cpp
src/preferencesdialog.h
src/saveimagejob.h
src/screenshotdialog.cpp
src/settings.cpp
src/settings.h

The comment in the code claim that there was no good way to use Qt for command-line parsing, but I found the solution provided by Qt to be much more clear and more appropriate. Using FM is also no longer needed in this function.

Replace glib with Qt for command-line parsing

---

CMakeLists.txt
src/CMakeLists.txt

To be merged after https://github.com/lxde/libfm-qt/pull/1 gets in.

CMake: Adapt to libfm-qt Targets

---

src/imageview.cpp
src/imageview.h
src/mainwindow.cpp
src/mainwindow.h

Adds support for GIF animation.

---

src/translations/lximage-qt_de.desktop

Fix typo in German translation for desktop file

---

src/translations/lximage-qt_pt.desktop

Capitalization in project name was wrong.
Thanks!

Fix typo in Portuguese translation for desktop file

---

src/application.cpp
src/application.h
src/imageview.cpp
src/mainwindow.cpp
src/screenshotdialog.cpp

Especially replaced the deprecated method `QPixmap::grabWindow()` with `QScreen::grabWindow()`.

Code cleanup

---

CMakeLists.txt
src/CMakeLists.txt

We already have an build time dependency on liblxqt. So, let's take all the
advantages we can.

Use LXQtCompilerSettings cmake module

---

data/lximage-qt.desktop.in

I don't see what they are needed for. Am I missing anything here?

Remove Core and Qt from Categories in desktop file

---

src/mainwindow.cpp

Corrected a wrong cast that deformed (scaled) images on rotation. (A bad typo plus a wrong assumption? I don't remember.)

Fixed A Cast

---

src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui

Display the first available image when opening a folder. Open a folder from
CLI and from a dialog, via the menu or Ctrl+D.
Thanks @tsujan for the reviews and suggestions.
Address lxde/lxqt#1117
Improve upon #72

[MRG] Display first image when loading a directory (v2)

---

src/CMakeLists.txt
src/screenshotdialog.cpp
src/screenshotdialog.ui
src/screenshotselectarea.cpp
src/screenshotselectarea.h
src/screenshotselectareagraphicsview.cpp
src/screenshotselectareagraphicsview.h

This PR only adds an option to capture an area of the screen.

Screenshot region

---

src/application.cpp

set Qt::AA_UseHighDpiPixmaps to true

---

.github/ISSUE_TEMPLATE.md

Copied issue-template

---

src/mainwindow.cpp

Fixes https://github.com/lxde/lximage-qt/issues/102.

Fix regression in thumbnail view

---

src/CMakeLists.txt
src/upload/imageshackprovider.cpp
src/upload/imageshackprovider.h
src/upload/imageshackupload.cpp
src/upload/imageshackupload.h
src/upload/uploaddialog.cpp

This pull request adds an upload provider for ImageShack, using their public API.

Add ImageShack upload provider

---

AUTHORS
src/imageview.cpp
src/loadimagejob.cpp
src/mainwindow.cpp

fix some http->https

---

src/loadimagejob.cpp
src/loadimagejob.h
src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui

This fixes the conflicts in https://github.com/lxqt/lximage-qt/pull/76
@rndevfx sorry for the long long delays. I fixed the conflicts in your PR and created a new PR for it.

render image EXIF data (by Rndevfx)

---

.gitattributes
.gitignore
.translation-update
src/translations/lximage-qt.ts

* don't export .translation-update
* refreshed base *.ts

Added .translation-update

---

src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui

This pull requests adds a button to the menu and toolbar for reloading the current image.

Add reload button

---

src/mainwindow.cpp

Fixes https://github.com/lxqt/lximage-qt/issues/200

Fixed thumbnail selection (with deletion)

---

src/CMakeLists.txt
src/upload/imgbbprovider.cpp
src/upload/imgbbprovider.h
src/upload/imgbbupload.cpp
src/upload/imgbbupload.h
src/upload/uploaddialog.cpp

This pull requests adds an upload provider for [ImgBB](https://imgbb.com/).

Add ImgBB upload provider

---

src/imageview.cpp
src/imageview.h
src/loadimagejob.cpp
src/mainwindow.cpp
src/mainwindow.h
src/preferencesdialog.cpp
src/saveimagejob.cpp
src/screenshotdialog.cpp
src/upload/imageshackprovider.cpp
src/upload/imgbbprovider.cpp

Hello :)
It's me again with yet another pull request on code style. I really hope this has not become annoying yet and there is a sense in it...
I have also checked the project with PVS studio, but I couldn't find any serious problem with it. Great job!

Codestyle improvements

---

src/loadimagejob.cpp

Closes https://github.com/lxqt/lximage-qt/issues/248

More complete transformation based on EXIF

---

src/mainwindow.cpp

Since the upload code needs a file path, the unsaved image (e.g., a screenshot) will be saved to `/tmp` and deleted after the upload is completed/canceled.
Fixes https://github.com/lxqt/lximage-qt/issues/273

Support uploading of unsaved images

---

src/application.cpp
src/application.h
src/preferencesdialog.cpp

Fixes https://github.com/lxqt/lximage-qt/issues/275

No multiple Preferences dialogs

---

src/mainwindow.cpp

Remove deprecated QDesktopWidget

---

src/mainwindow.cpp
src/mainwindow.h
src/mainwindow.ui

The user can assign a shortcut to it in the shortcut editor.

Added copy Path action

---

src/translations/lximage-qt_it.ts

Co-authored-by: Standreas <ste@vogliaditerra.com>
Translate-URL: http://135.181.85.100/projects/lxqt-desktop/lximage-qt/it/
Translation: LXQt Desktop/lximage-qt

Weblate commits

---

src/mainwindow.cpp

Start app on screen with mouse cursor when opening image

---

src/application.cpp

About which, the compiler didn't give an error.

Added missing parentheses

---

src/mainwindow.cpp
src/preferencesdialog.cpp
src/preferencesdialog.ui
src/settings.cpp
src/settings.h

Implement force zoom fit when loading images.

---

src/mainwindow.cpp
src/preferencesdialog.cpp
src/preferencesdialog.ui
src/settings.cpp
src/settings.h

Add an option to use the system trash instead of immediately deleting files.

Add option to use system Trash

---

src/mainwindow.cpp
src/preferencesdialog.cpp
src/preferencesdialog.h
src/preferencesdialog.ui
src/settings.cpp
src/settings.h

Add option in preferences to set preferred thumbnail size.

Add option to change Thumbnail dimensions

---

src/mainwindow.cpp

Fixes https://github.com/lxqt/lximage-qt/issues/444
Supercedes https://github.com/lxqt/lximage-qt/pull/446

Fixed wheel scrolling on image with touchpad

---

src/mainwindow.cpp

Added reprository link to About dialog

---

src/imageview.cpp
src/imageview.h
src/mainwindow.cpp
src/preferencesdialog.cpp
src/preferencesdialog.ui
src/settings.cpp
src/settings.h

Added option to disable blur filter on zoom

---

src/mainwindow.ui

Fixes https://github.com/lxqt/lximage-qt/issues/519
Added also a shortcut.

Move upload entry, add shortcut

---

data/lximage-qt-screenshot.desktop.in

Removed since it's deprecated.

Removed Screenshot Desktop file

---

README.md

Closes https://github.com/lxqt/lximage-qt/issues/592

Added a note on `kimageformats` to README

---

data/lximage-qt.desktop.in

And alphabetize the MIME type list to make it easy to tell what's included and what's not.

Add image/webp to lximage-qt.desktop

---

README.md
data/lximage-qt.metainfo.xml
src/translations/lximage-qt.desktop.yaml
src/translations/lximage-qt_bg.desktop.yaml
src/translations/lximage-qt_ca.desktop.yaml
src/translations/lximage-qt_cs.desktop.yaml
src/translations/lximage-qt_da.desktop.yaml
src/translations/lximage-qt_de.desktop.yaml
src/translations/lximage-qt_el.desktop.yaml
src/translations/lximage-qt_es.desktop.yaml
src/translations/lximage-qt_et.desktop.yaml
src/translations/lximage-qt_fi.desktop.yaml
src/translations/lximage-qt_fr.desktop.yaml
src/translations/lximage-qt_gl.desktop.yaml
src/translations/lximage-qt_he.desktop.yaml
src/translations/lximage-qt_hr.desktop.yaml
src/translations/lximage-qt_it.desktop.yaml
src/translations/lximage-qt_ja.desktop.yaml
src/translations/lximage-qt_ko.desktop.yaml
src/translations/lximage-qt_lt.desktop.yaml
src/translations/lximage-qt_nb_NO.desktop.yaml
src/translations/lximage-qt_nl.desktop.yaml
src/translations/lximage-qt_oc.desktop.yaml
src/translations/lximage-qt_pl.desktop.yaml
src/translations/lximage-qt_ru.desktop.yaml
src/translations/lximage-qt_sk.desktop.yaml
src/translations/lximage-qt_sl.desktop.yaml
src/translations/lximage-qt_tr.desktop.yaml
src/translations/lximage-qt_uk.desktop.yaml
src/translations/lximage-qt_vi.desktop.yaml

Also fix capitalization in several places

Replace instances of 'LXImage' with 'LXImage-Qt' in desktop entries

---

src/mainwindow.cpp
src/preferencesdialog.cpp
src/preferencesdialog.h
src/preferencesdialog.ui
src/settings.cpp
src/settings.h

… as far as Qt allowed.
Closes https://github.com/lxqt/lximage-qt/issues/320

Added minimal support for color spaces

---

data/lximage-qt.desktop.in

Closes https://github.com/lxqt/lximage-qt/issues/673

Corrected a misspelled mimetype

---

src/imageview.cpp
src/imageview.h

Fixes https://github.com/lxqt/lximage-qt/issues/698

Fixed a problem in rectangular annotation

---

src/mainwindow.cpp

Closes https://github.com/lxqt/lximage-qt/issues/736

Support animated WebP images

---

src/mrumenu.cpp
src/mrumenu.h

Exactly the same as https://github.com/lxqt/pcmanfm-qt/pull/2081 but for LXImage-Qt

Fix showing of ampersand in recent files menu

---

src/mainwindow.cpp
src/statusbar.cpp

Closes https://github.com/lxqt/lximage-qt/issues/741

Show dimensions of pasted image on status-bar
