- src/saveimagejob.cpp
With this flag, the default file permissions seems to be used when
creating new files, and permissions to existing files are conserved when
saving (except when changing the permission explicitely of course).
See: http://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gio/GFile.html#GFileCreateFlags
Fixes #25.
> Don't save file in private mode

- src/imageview.cpp
To generate the cached pixmap for scaled images, only the raw data was used, without considering the color table. Without the color table, the produced pixmap is not correct, in particular this caused the problem seen in issue #6, when the screen is black, it's because the cached pixmap with the wrong color table is displayed, this is why you can catch a glimpse of the original image before the pixmap is loaded, and also why the image is displayed properly when no scaling is applied.
This pull request ensures that the color table, if present, is used to generate the pixmap, thus fixing issue #6.
> Set the color table properly for scaled images

- src/screenshotdialog.cpp
There were two local variables with the same name in different scopes. The second variable stored the pointer but only the first was deleted.
Thanks!
> Fix memory leak if taking screenshot with cursor

- src/translations/lximage-qt_ru.desktop
The Russian translation for the desktop entry was not included into the final desktop file because its keys did not end with the locale postfix.
Thanks!
> Fix missing Russian translation in desktop file

- src/application.cpp
- src/mainwindow.cpp
By clicking on an image for the first time, the user wants to see it clearly with lximage-qt. So, the following behavior is implemented here:
(1) A minimum size of 400x400 is assumed;
(2) The window is scaled to fit the image;
(3) For too big images, the window is scaled down;
(4) The window is centered on the screen.
(5) The loaded image is selected and centered in the thumbnail view.
This also addresses #43.
> Implement an EOG-like behavior on starting

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
This commit hides the cursor in the fullscreen mode after 3 seconds of inactivity and shows it again when needed.
> Hide cursor smartly in fullscreen mode

- CMakeLists.txt
- src/CMakeLists.txt
- src/application.cpp
- src/application.h
- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
Fixes https://github.com/lxde/lximage-qt/issues/49 by using QGraphicsSvgItem.
Also the zoom-in shortcut is fixed and a shortcut is added for zooming to the original size.
BTW, this PR also enables lximage-qt to show SVG animations as far as they're supported by Qt.
> Treat SVG files separately as SVG images

- src/application.cpp
- src/imageview.cpp
- src/job.cpp
- src/loadimagejob.cpp
- src/mainwindow.cpp
- src/preferencesdialog.cpp
- src/saveimagejob.cpp
- src/settings.cpp
Thanks to, https://github.com/lxde/lximage-qt/pull/58/commits/8c52c8ddf0a14369d6b0f53e7672992294d2d287, a problem is also found and fixed.
A warning related to `g_io_scheduler_job_send_to_mainloop()` remains. I think @PCMan might fix it better than I could.
> Quieten compiler warning

- src/CMakeLists.txt
- src/graphicsscene.cpp
- src/graphicsscene.h
- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
Fixes https://github.com/lxde/lximage-qt/issues/69.
A file/folder can be dropped into lximage-qt's view and it will be opened if it is/contains a valid image.
> File and folder DND

- src/preferencesdialog.cpp
Avoid assignment of a non-const pointer to a const pointer and the
consequent container detach.
> Use const iterators

- src/mainwindow.cpp
> MainWindow: Fix crash for quick image changes

- src/CMakeLists.txt
This way we don't make assumptions about install dirs. And we give the
packager the ability to override CMAKE_INSTALL_DATAROOTDIR.
> Don't use hardcoded install dir

- CMakeLists.txt
- src/CMakeLists.txt
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/upload/imgurprovider.cpp
- src/upload/imgurprovider.h
- src/upload/imgurupload.cpp
- src/upload/imgurupload.h
- src/upload/provider.cpp
- src/upload/provider.h
- src/upload/upload.cpp
- src/upload/upload.h
- src/upload/uploaddialog.cpp
- src/upload/uploaddialog.h
- src/upload/uploaddialog.ui
I decided to take a stab at bug #98.
The user interface I came up with is fairly simple.
1. The user clicks the "Edit->Upload" menu item and selects a provider:
2. The image is uploaded asynchronously:
3. Upon successful completion, the URL of the image is shown:
Under the hood, I introduced a few new classes:
- UploadDialog takes care of presenting the UI to the user and displaying the status of the upload
- Provider is a base class for creating Upload objects, given a file opened for reading
- Upload is returned by Provider and emits signals to indicate upload status
This pull request includes support for Imgur uploads but the code is designed to easily allow more services to be supported.
> Add support for uploading files

- src/application.cpp
- src/mainwindow.cpp
- src/mainwindow.h
- src/modelfilter.cpp
As mentioned in issue #112, there are a handful of lines that cause compiler warnings when building lximage-qt. This pull request fixes the warnings by:
- removing unnecessary semicolons at the end of namespace declarations
- squelching warnings about unused parameters with `Q_UNUSED()`
- removing unused parameters captured by lambdas
I have tested this against both GCC 7.2 and Clang 5
> Fix warnings issued by GCC and Clang.

- src/mainwindow.h
lifm-qt no longer depends on libfm.
> Fix a FTBFS due to libfm header inclusion

- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
I add the following keyboard shortcuts in this PR:
- Esc -> exit
- h -> flip horizontally
- r -> rotate clockwise
- l -> rotate counter clockwise
- t -> show/hide thumbnails
- space -> next image
- backspace -> previous image
I did not implement showing/hiding the toolbar via a keyboard shortcut, because I did not find a simple way to do it. But maybe there is one, if someone points me into the right direction I will implement it. But I also think that hiding the toolbar via keyboard is not that often used.
Fixes #92
> Added more keyboard shortcuts

- src/mainwindow.cpp
Add confirmation dialog when using "Save as" with a filename without extension. Fixes #109
> Fixes issue 109

- src/CMakeLists.txt
use XFIXES_LDFLAGS so Clang linker can find the libXfixes library (FreeBSD)
> use XFIXES_LDFLAGS

- CMakeLists.txt
Nice big bump to prevent conflicts with translations that are former built from
lxqt-l10n and have version 0.13.x
> Bump minor version to 14

- src/upload/uploaddialog.cpp
- src/upload/uploaddialog.h
- src/upload/uploaddialog.ui
This pull request adds a copy button to the upload dialog for easily copying the link to the clipboard:
> Add copy button to upload dialog

- src/CMakeLists.txt
- src/mainwindow.cpp
- src/mainwindow.ui
- src/mrumenu.cpp
- src/mrumenu.h
- src/settings.cpp
- src/settings.h
This pull request adds a menu that shows recently opened files, enabling the user to quickly return to an image that was opened previously:
> Implement MRU list

- src/mainwindow.cpp
- src/mainwindow.ui
Seeing 'toolBar_2' looks just a little bit odd in the context menu.  :]
I first went with 'Toolbar 2', but then I realised its name is already 'annotationsToolBar' elsewhere, so I decided to go with that instead.
I'm not sure if the intention was to not hide this one in full screen mode, so as to be able to annotate while in said mode.  I can de-select the toolbar, but the setting isn't remembered (and if it was remembered, it would probably be hidden when exiting full screen mode too, which might be weird).
That said, it would be nice to be able to remove, and keep them both bars removed via the preferences, or perhaps the view settings.
> ui: rename user-visible 'toolBar_2', and hide it in full screen mode

- src/mainwindow.ui
File -> File don't make sense and is not consistent with nearly all other™
Software around (Inkscape, Gimp, LO, Geany and so on)
Should be Open… (with Ellipsis instead of three point). We should change
'...' to '…' projectwide, all people will hate us and esp. me, esp the translators,
but hey - we really should do that.
> Fix the file open string

- src/mainwindow.cpp
- src/mainwindow.ui
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
This patch hides it by default (because lximage-qt is an image *viewer*, not editor) but adds an option to Preferences to show it by default. It also adds an item to the View menu to show/hide it in the current window.
> An option to show/hide annotations toolbar by default

- src/mainwindow.cpp
Because libfm-qt tooltips are more informative now and we don't want an item to be selected on showing its tooltip.
Also, made thumbnail icon size 64 px — 48 px was too small for a thumbnail.
> No auto-selection in thumbnail view

- src/mainwindow.cpp
Previously, no image was shown.
Also, select the current image on file opening and the current directory on directory opening if they exist; otherwise, open the home folder.
> Fixed showing first image on loading a directory

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
Closes https://github.com/lxqt/lximage-qt/issues/196
It is useful for checking the space around an image/icon.
Also found and fixed a small hidden bug about showing next/previous image.
> Optionally show image outline

- src/imageview.cpp
- src/imageview.h
Fixes https://github.com/lxqt/lximage-qt/issues/242
Previously, when Qt scale factor was greater than 1, (unscaled) images became blurry. This patch fixes the problem by setting the device pixel ratio of the image to that of the app and also by considering it in calculating sizes. In short, images are shown with their real sizes.
Also cleaned up the code for image outline and fixed a small issue in it.
> Prevent blurry images with HDPI

- src/mainwindow.cpp
- src/mainwindow.h
Fixes https://github.com/lxqt/lximage-qt/issues/187
If there are other images, the next one will be shown (or the previous one if the last image is deleted); otherwise, a blank view will be shown (even when the image is renamed).
> Jump forward when the image is deleted/renamed

- src/application.cpp
- src/mainwindow.cpp
Because it's limited to X11 and causes a crash under Wayland.
> Remove X11 screenshot under Wayland

- src/mainwindow.cpp
- src/mrumenu.cpp
- src/mrumenu.h
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
If it's set to 0, it'll be disabled. It can be from 0 to 99 but the default is 5, as before.
Also closes https://github.com/lxqt/lximage-qt/issues/270
> Made maximum number of recent files configurable

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/screenshotdialog.cpp
Also, resize the screenshot window to the last window size (as is done for new windows).
Closes https://github.com/lxqt/lximage-qt/issues/190
> Keep zooming state on switching image

- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
It will be enabled only if a file is opened in lximage-qt.
NOTE: The code could be enhanced so that pasted images or unsaved screenshots would also be opened in other apps. That would require saving them in `/tmp` but I don't think it's a good idea because the temporary file would remain there after being opened by another app. That's the case with apps like Screengrab too (when Screengrab exits *after* its unsaved screenshot is opened by another app).
Closes https://github.com/lxqt/lximage-qt/issues/289
> Added "Open With.." to File menu

- src/mainwindow.cpp
Previously, a large image was divided and cut. Now, it fits into the page.
The code of the old behavior is commented out, not removed.
NOTE: I tested it only with PDF.
Fixes https://github.com/lxqt/lximage-qt/issues/263
> Fixed image printing

- src/application.cpp
Slightly enhance `-dirscreenshot` cmdline arg description and its translatability.
Before the patch the `--help` message looked pretty strange because of too long optional arg name:
```
...
-s, --screenshot                            Take a screenshot
-d, --dirscreenshot <folder_to_save_files>  Take a screenshot to folder
without gui
```
Now it looks slightly better:
```
...
-s, --screenshot           Take a screenshot
-d, --dirscreenshot <DIR>  Take a screenshot and save it to the directory
without showing the GUI
```
The patch enable localization of the `DIR` argument itself as well.
Also as was pointed on the weblate's [comment][1], the help message was a bit obscure.
<hr>
PS: shouldn't this functionality be moved to the `screengrab`?
[1]: …
> Enhance `-dirscreenshot` cmdline arg description.

- src/screenshotdialog.ui
Use "sec" suffix instead of "seconds" for the delay spinbox, because
the second one doesn't play well with value==1 and looks even worse in
translations.
> screenshotdialog: use shorter suffix in the delay spinbox

- src/application.cpp
- src/application.h
- src/mainwindow.cpp
- src/preferencesdialog.cpp
- src/preferencesdialog.h
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
All actions can have custom shortcuts, those without shortcuts included. Shortcuts can also be removed by entering a modifier key.
Also, Preferences dialog's size is remembered.
NOTE: Qt ≥ 5.13 has a bug about the Meta key. A partial workaround is included, so that Meta can be used in key combinations. It is partial because Meta is temporarily shown as a group of meaningless characters but they disappear afterward. See https://bugreports.qt.io/browse/QTBUG-62102
Closes https://github.com/lxqt/lximage-qt/issues/293
> Added shortcut editor to Preferences

- src/mainwindow.cpp
- src/mainwindow.h
The root of this minor problem was deeper than meets the eye: with SVG and GIF, the maximization info was lost when we resized the window before showing it. This may be a bug in Qt. The patch remembers the maximization info and applies it when the window is going to be shown.
Fixes https://github.com/lxqt/lximage-qt/issues/301
> Fixed maximization at startup with SVG and GIF images

- src/CMakeLists.txt
- src/mainwindow.cpp
- src/mainwindow.ui
- src/statusbar.cpp
- src/statusbar.h
The path text will be elided if needed.
The title-bar info is kept intact.
Closes https://github.com/lxqt/lximage-qt/issues/193
> Added image size and path to statusbar

- src/imageview.cpp
- src/imageview.h
The reason for this bug is that when paintdevice is a widget,
QPainter can only be used inside a paintEvent() function or in a
function called by paintEvent()
this commit fix this bug by drawing the same rectangle in the scene
LXImage use QGraphicsView to display image and QGraphicsView is a
part of the Grapics View Framework. Usually by calling update(), a
widget is able to trigger paintEvent(). However, as far as i know,
in the Graphics View Framework, it's impossible for QGraphicsView
to tigger the paintEvent() by calling update()
so i choose the Graphics View Framwork way to draw the rectangle
something like: scene.addRect(...)
> fix bug #307 : drawing rectangle doesn't show

- src/imageview.cpp
- src/imageview.h
There were memory leaks with SVG and GIF.
NOTE: The annotations code structure is suboptimal for various reasons and might need a refactoring later.
> Fixed memory leaks in annotations

- src/mainwindow.cpp
- src/saveimagejob.cpp
For example, images cannot be saved as SVG or GIF and it's better to inform the user about that, instead of creating an empty file or, worse, overwriting an existing image.
Also, corrected `MainWindow::getImageGraphicsItem()` because it didn't take a recent annotations commit into account (annotations are now added as items).
> Show error message if saving with a format is not supported

- src/screenshotdialog.h
Using 0/nullptr is deprecated.
> Use QFlags default constructor

- src/application.cpp
- src/preferencesdialog.cpp
- src/preferencesdialog.h
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
If the user tries to define an ambiguous shortcut, the shortcut will not change but a temporary warning bar will appear at the bottom of Preferences dialog for 2.5 seconds.
In addition, if an ambiguous shortcut was defined by editing the config file (while lximage-qt was closed) or by an older version of lximage-qt, a permanent warning bar will appear. It will be removed once the ambiguity is resolved.
Also:
* Added a tooltip about shortcut removal; and
* Fixed a bug in defining a shortcut for the annotation toolbar.
NOTE: I'll update the translations after this is merged.
Closes https://github.com/lxqt/lximage-qt/issues/330
> Prevent users from defining ambiguous shortcuts

- src/application.cpp
LXQt's screenshot utility is screengrab and the current X11 screenshot code may be removed from lximage-qt sooner or later
> Add depreciation notice to screenshot command line options, closes #334

- src/modelfilter.cpp
Previously, the code used `Fm::FileInfo::isImage()`, which only checks if the mimetype starts with "image/", while Qt may support more.
Closes https://github.com/lxqt/lximage-qt/issues/336
> Consult Qt for supported mimetypes

- src/loadimagejob.cpp
- src/mainwindow.cpp
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
- src/upload/upload.cpp
Two options are added: showing thumbnails dock by default and setting the max. file size for creating thumbnails.
No option is added for disabling thumbnails because this is an image viewer.
Also, silenced two compilation warnings about `QNetworkReply::error` and `QMatrix` and changed a bad translatable string that was added in https://github.com/lxqt/lximage-qt/commit/502530154d61d9e46213908292ecc8a7c0e0520c
> Added options for thumbnails

- src/mainwindow.cpp
- src/mainwindow.h
And override WM focus stealing prevention as far as possible.
NOTE: This doesn't work under Wayland but Wayland's impractical situation can't be our concern.
Closes https://github.com/lxqt/lximage-qt/issues/427
> Try best to raise new windows

- src/imageview.cpp
- src/mainwindow.cpp
- src/org.lxde.LxImage.Application.xml
Fixes https://github.com/lxqt/lximage-qt/issues/433 (and more).
Also, added the new argument of introspection data for staring in full-screen mode, which I'd forgotten in https://github.com/lxqt/lximage-qt/commit/8d122f2a48641fa955f0dabbc44035f05d690348
> Fixed bugs in image fitting, especially with thumbnail dock

- src/mainwindow.cpp
- src/preferencesdialog.cpp
- src/preferencesdialog.h
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
This adds an option to move the Thumbnail dock to different sides of the main window.
> Add option to change Thumbnail dock position

- src/mainwindow.cpp
- src/mainwindow.h
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
This adds an option to preferences to show/hide the Exif dock at startup.
> Add option to show/hide Exif dock at startup

- src/preferencesdialog.ui
- src/settings.cpp
Proposed reorganization of preferences.
>  Reorganize preferences dialog 

- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
Currently, the only way to create a shortcut to rename a file is to use the File Properties dialog.  This change allows direct access to inline renaming when the thumbnail bar is visible.  When thumbnails are not visible, the libfm-qt rename dialog is shown.
> Allow creation of shortcut to rename image directly

- src/mainwindow.cpp
- src/mainwindow.ui
- src/preferencesdialog.cpp
- src/preferencesdialog.ui
- src/settings.cpp
- src/settings.h
This is just the final feature needed for a "minimal" interface (#283 and #284).  There is no option in the menubar to hide the menubar because hiding it that way may confuse users who don't know how to restore it.  There is a context menu option and default shortcut Ctrl+M so that the menu may be restored when it is hidden.
I also assigned a default shortcut for renaming, since I had overlooked that earlier.
> Add option to show/hide menubar

- src/mainwindow.cpp
- src/preferencesdialog.cpp
- src/settings.cpp
- src/settings.h
Excluded right area (because it's used by EXIF data) and fixed localization of position strings.
@stefonarch, please merge it if your tests show it's OK. After that, you could update translations; my next PR won't add a translatable string.
> Fixed issues in a recent commit about thumbnails positions

- src/mainwindow.cpp
It was caused by a typo in the second argument of `QImage::mirrored` and made images also flip vertically when they were made smaller than their original sizes.
Fixes https://github.com/lxqt/lximage-qt/issues/470
> Fixed horizontal flipping of resized images

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
Fixed several issues in rotation and flipping
All issues are fixed by:
1. Resetting transformations when an image is loaded;
2. Giving the same code structure to flipping and rotation; and
3. Loading a saved image (lack of this was a bug in itself).
In addition, the code is cleaned up with regard to image transformation and, as a result, other small bugs are also fixed.
Fixes https://github.com/lxqt/lximage-qt/issues/472
> Fixed several issues in rotation and flipping

- src/mainwindow.cpp
Closes https://github.com/lxqt/lximage-qt/issues/473
@stefonarch 
The translatable strings are split for keeping them intact after version/copyright changes. Only one translatable string needs to be changed in such cases: "2013-2021"; in most languages, it doesn't need a translation.
> Improved About dialog

- src/mainwindow.cpp
- src/mainwindow.h
- src/preferencesdialog.cpp
- src/preferencesdialog.h
Also, a small mistake in the calculation of thumbnail-bar's height/width is fixed (the frame width wasn't taken into account).
Closes https://github.com/lxqt/lximage-qt/issues/477
> Apply changes to thumbnail size on the fly

- src/CMakeLists.txt
- src/application.cpp
- src/application.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/preferencesdialog.cpp
- src/shortcuts.ui
With this patch, hard-coded shortcuts (Escape → exiting/un-fullscreen, Space and Right → next image, Backspace and Left → previous image) can be overridden by custom shortcuts. Previously, overriding resulted in ambiguity, so that the shortcut was disabled.
Also, two hard-coded shortcuts and a "Hidden Shortcuts" dialog are added. The latter tells the user about overriding too.
In addition, the code is cleaned up with regard to custom shortcuts.
Fixes https://github.com/lxqt/lximage-qt/issues/475
> Allow custom shortcuts to override hard-coded shortcuts

- src/mainwindow.cpp
The best method of fullscreening is check the maximized state before fullscreening and restore it on un-fullscreening. Previously, `showFullScreen()` was used; it removed the max state before fullscreening.
> Restore maximized state (if any) on un-fullscreening

- src/screenshotselectarea.cpp
#522 (already closed)
when selecting option "Capture an area of the screen" the dialog for selection will cover all screens.
> [ScreenShot] option "Capture an area of the screen" covers all screens

- src/imageview.cpp
Previously, the cached pixmap was drawn inside the repaint rectangle. That was wrong because there's no guarantee that the repaint rectangle is as big as the cached pixmap (e.g., it isn't so when the toolbar extension popup covers a part of the image and slides back). Therefore, visual glitches were imminent in special cases.
This patch draws the cached pixmap inside its corresponding cache rectangle, so that the image is always repainted correctly. The paint clipping is done by Qt automatically, as QPaintEvent's doc explains.
Fixes https://github.com/lxqt/lximage-qt/issues/557
> Fixed repainting of cached images

- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/settings.cpp
- src/settings.h
The app remembers sorting by name, file size, file type, modification time and creation time. Other kinds of sorting are ignored.
Closes https://github.com/lxqt/lximage-qt/issues/574
> Added Sorting sub-menu to View menu

- src/mainwindow.ui
- src/mrumenu.cpp
5 menu icons added to LXImage-Qt's toolbar: namely 'document-print', 'object-flip-horizontal', 'object-flip-vertical', 'document-properties', and 'edit-clear'.
The icons exist in well-known icon sets; the Adwaita icon set has them but in "-symbolic" form.
> Add 5 icons to the toolbar menus

- src/imageview.cpp
This is similar to https://github.com/lxqt/lxqt-notificationd/pull/375. Both fixes are logical, regardless of what has changed in Qt 6.7.
> Fixed a crash on using annotations with Qt ≥ 6.7

- src/mrumenu.cpp
Let Qt parent/child mechanism handle it's destruction. Found by ASAN.
> Fix memory leak

- src/mainwindow.cpp
Stumbled upon that while updating translations - existing translations are often outdated if not wrong:
```
$   <translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>Kattaa vuodet 2013-2022</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013-2021</translation>
<translation>2013. – 2021.</translation>
<translation>2013-2021</translation> …
```
> Remove useless translation

- src/screenshotselectarea.cpp
Set QFrame::NoFrame on ScreenshotSelectAreaGraphicsView to prevent the main view from being oversized. Previously it's possible to use the arrow keys to shift the view 1px.
Additionally, another change should be made for allowing to select the entire screen area (it's off my 1px regardless of this.)
> Small fix to screenshot select area

- AUTHORS
- data/lximage-qt.metainfo.xml
Fixes https://github.com/lxqt/lximage-qt/issues/645
All files in /src have the header below, I don't see any need for adding  LGPL-2.1+ anywhere.
```
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
```
> Cleanup licenses

- src/application.cpp
Qt6 started to set an allocation limit of 256 MiB. The behavior of Qt5 is restored here, i.e., no limit is set, because this is an image viewer.
Closes https://github.com/lxqt/lximage-qt/issues/690
> Don't set a limit for image size

- src/mainwindow.h
- src/upload/imgbbprovider.cpp
- src/upload/imgbbprovider.h
- src/upload/imgurprovider.cpp
- src/upload/imgurprovider.h
- src/upload/provider.cpp
- src/upload/provider.h
- src/upload/uploaddialog.cpp
- src/upload/uploaddialog.h
`QNetworkAccessManager` is changed to a static `QPointer`, which is deleted when all instances of `Provider` are deleted.
In addition, all providers are created on the heap, as children of the upload dialog.
In this way, the following warning is silenced:
```
qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
```
> Fixed invalid nullptr parameter in `QObject::connect`

- src/imageview.cpp
- src/screenshotselectareagraphicsview.cpp
Converstion of `QRectF` to `QRect` excludes the right and bottom edges. That's taken into account by the patch.
Also, the deprecated method `QMouseEvent::pos()` is replaced.
> Fixed a small miscalculation in selection screenshot

- src/mainwindow.cpp
Previously, the thumbnail of the current image might be outside the visible part of the thumbnail bar when the app was started, although the code tried to scroll to it.
> Ensure current thumbnail is in visible part of thumbnail bar

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
On Wayland, each screen can have its own device pixel ratio, which is correctly reported by the window, not by the app.
The app's behavior under X11 is like before.
Closes https://github.com/lxqt/lximage-qt/issues/701
> Use the device pixel ratio of the window on Wayland

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/settings.cpp
The issues were bizarre — especially in one case, all relevant Qt methods gave wrong pixel ratios — but workarounds were effective.
Also,
* Fixed an old issue in showing GIF animations with pixel ratios > 1;
* Commented out "RememberWindowSize" from settings because it was never used (but might be used later); and
* Removed a redundant private variable.
Closes https://github.com/lxqt/lximage-qt/issues/703
> Fixes and workarounds for multi-screen scaling issues on Wayland

- src/mainwindow.ui
See PCManFM-Qt's usage
Also "Recently Opened Files" is a bit verbose - replace with "Recent Files"? Regardless, I did not want to change translations.
> Add document-open-recent icon to "Recently Opened Files"

- src/imageview.cpp
Since Qt 6.9, image flipping is done by `QImage::flipped`. A version check is added.
> Silenced compilation warning about `QImage::mirrored`

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
If a multi-page TIFF image is opened, the menu-items "Next Frame" and "Previous Frame" will be added to the "Go" menu, with the shortcuts "Ctrl+Right" and "Ctrl+Left" respectively. Of course the shortcuts can be changed in the shortcut editor.
To prevent cluttering of the GUI for this special use case, I didn't add another way of informing the users. They should either check the "Go" menu or press those shortcuts to see whether a TIFF image includes multiple pages.
Closes https://github.com/lxqt/lximage-qt/issues/721
> Supported multi-page TIFF images

- src/imageview.cpp
- src/imageview.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/mainwindow.ui
- src/statusbar.cpp
- src/statusbar.h
The changes:
1. Two extra actions are added for going to the first and last frames.
2. A label appears on the right side of the status-bar, which shows the current frame and the total number of frames.
3. On saving, the current frame is saved, with all applied transformations.
4. On copying to clipboard, the current frame is copied, with all applied transformations.
5. The annotations are cleared on changing the frame. The reason is twofold: first, this is consistent with changing the viewed image; second, the annotations could be saved only if they are applied to the current frame.
> More complete support for multi-page TIFF images

- src/mainwindow.cpp
- src/mainwindow.h
Actually, a redundant private variable, that could become a source of trouble, has been removed, and as a result, copying annotations is fixed automatically.
Fixes https://github.com/lxqt/lximage-qt/issues/727
> Fixed copying annotations to clipboard

- src/application.cpp
This ensures that the icon is set on all windows on X11.
Similar to https://github.com/lxqt/pcmanfm-qt/pull/2096, the non-modal preferences window has no icon on X11 without this.
> Set window icon

- src/mainwindow.cpp
This ensures that the dialog is attached to the main window.
> Assign the print dialog to the parent window
